language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"

before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - mkdir .cpanreporter
  - echo "edit_report=no\nemail_from="Michael Arnold" <michael@rnold.info>\nsend_report=yes\ntransport=Metabase uri https://metabase.cpantesters.org/api/v1/ id_file metabase_id.json" > .cpanreporter/config.ini

install:
  - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cpanm --quiet --notest --installdeps .

script:
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
  - cover

after_success:
  - cover -report coveralls
  - cpanm-reporter
